-- migrate:up
CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
name VARCHAR(30) NOT NULL,
updated_at DATETIME  NOT NULL DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP,
created_at DATETIME  NOT NULL DEFAULT NOW()
);

-- migrate:down
DROP TABLE users;
